package expo.modules.yandexmap.model

const val INFO_TAG = "INFO_TAG"
const val ERROR_TAG = "ERROR_TAG"

const val MAPKIT_API_KEY = "MAPKIT_API_KEY"

const val DEFAULT_CLUSTER_RADIUS = 60.0
const val DEFAULT_CLUSTER_ZOOM = 15
const val INITIAL_CAMERA_ZOOM = 13f
const val DEFAULT_CLUSTER_TILT = 0f
const val DEFAULT_CLUSTER_AZIMUTH = 0f

const val MARKER_DEFAULT_TEXT_SIZE = 10.0F
const val MARKER_DEFAULT_OUTLINE_WIDTH = 1.0F
const val MARKER_DEFAULT_OFFSET = 0.0F

const val DEFAULT_CLUSTER_STROKE_COLOR = "#2196F3"
const val DEFAULT_CLUSTER_STROKE_WIDTH = 2