let MAPKIT_API_KEY = "MAPKIT_API_KEY"

let DEFAULT_CLUSTER_BACKGROUND = "#FFFFFF"
let DEFAULT_CLUSTER_STROKE_COLOR = "#2196F3"
let DEFAULT_CLUSTER_TEXT_COLOR = "#000"
let DEFAULT_CLUSTER_RADIUS = 60.0
let DEFAULT_CLUSTER_ZOOM = 15.0
let DEFAULT_CLUSTER_STROKE_WIDTH: Float = 2.0
let DEFAULT_CLUSTER_PADDING = 6
let DEFAULT_CLUSTER_FONT_SIZE: Float = 14.0

let INITIAL_CAMERA_ZOOM: Float = 13.0
